# Override this profile for local dev: mvn spring-boot:run -Dspring-boot.run.profiles=local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    show-sql: true
